// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSRS_TeamProject.Data;

#nullable disable

namespace OSRS_TeamProject.Migrations
{
    [DbContext(typeof(GameInvContext))]
    partial class GameInvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("OSRS_TeamProject.Models.InventoryItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            ItemId = 4151,
                            IconUrl = "/img/placeholder-item.svg",
                            Name = "Abyssal whip",
                            Notes = "Goal: 70 Attack",
                            Quantity = 1
                        },
                        new
                        {
                            ItemId = 1127,
                            IconUrl = "/img/placeholder-item.svg",
                            Name = "Rune platebody",
                            Notes = "Melee set",
                            Quantity = 1
                        },
                        new
                        {
                            ItemId = 379,
                            IconUrl = "/img/placeholder-item.svg",
                            Name = "Lobster",
                            Notes = "Food for slayer",
                            Quantity = 12
                        },
                        new
                        {
                            ItemId = 561,
                            IconUrl = "/img/placeholder-item.svg",
                            Name = "Nature rune",
                            Notes = "High alch stack",
                            Quantity = 150
                        },
                        new
                        {
                            ItemId = 1521,
                            IconUrl = "/img/placeholder-item.svg",
                            Name = "Oak logs",
                            Notes = "Fletching later",
                            Quantity = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
